version: "3.8"

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents overwriting node_modules
    command: ["npm", "run", "dev"]
    networks:
      - shared-dev-net
    environment:
      - MONGODB_URI=mongodb+srv://nayan:eVUUzkXbnqJezyQV@cluster0.ujzmxlu.mongodb.net

networks:
  shared-dev-net:
    external: true
